version: '0.0'
os: linux
files:
  - source: manifests/
    destination: /manifests  
  - source: scripts/
    destination: /manifests/scripts
hooks:
   AfterInstall:
    - location: scripts/manifests.sh
      timeout: 300
      runas: root
