apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: watch-store-ingress
  namespace: watch-app
  labels:
    app: watchstore
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    alb.ingress.kubernetes.io/target-type: ip
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend-service
                port:
                  number: 80
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: backend-service
                port:
                  number: 4000
