apiVersion: v1
kind: Secret
metadata:
  name: watch-app-secret
  namespace: watch-app
type: Opaque
stringData:
  SMTP_USER: "${SMTP_USER}"
  SMTP_PASS: "${SMTP_PASS}"
  PASSWORD_SALT: "${PASSWORD_SALT}"
  DB_PASSWORD: "${DB_PASSWORD}"
