-- PostgreSQL Normalized Schema for Watch Store (3NF)

-- ── Lookup / reference tables ─────────────────────────────────

CREATE TABLE IF NOT EXISTS brands (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS categories (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS movements (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS case_materials (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL UNIQUE
);

-- ── Users ────────────────────────────────────────────────────

DO $$
BEGIN
  CREATE TYPE user_role AS ENUM ('user', 'admin');
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

CREATE TABLE IF NOT EXISTS users (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    email_verified BOOLEAN NOT NULL DEFAULT FALSE,
    email_verified_at TIMESTAMP NULL,
    role USER_ROLE NOT NULL DEFAULT 'user',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- A user may have multiple saved addresses / phone numbers
CREATE TABLE IF NOT EXISTS user_addresses (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INT NOT NULL,
    phone VARCHAR(50) NOT NULL,
    address TEXT NOT NULL,
    city VARCHAR(100) NOT NULL,
    is_default BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);

-- ── Products (watches) ───────────────────────────────────────

CREATE TABLE IF NOT EXISTS watches (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    brand_id INT NOT NULL,
    category_id INT NOT NULL,
    movement_id INT NOT NULL,
    case_material_id INT NOT NULL,
    price DECIMAL(12, 2) NOT NULL,
    original_price DECIMAL(12, 2) DEFAULT NULL,
    primary_image TEXT NOT NULL,
    water_resistance VARCHAR(100) NOT NULL,
    warranty VARCHAR(255) NOT NULL,
    case_size VARCHAR(100) NOT NULL,
    description TEXT NOT NULL,
    stock INT NOT NULL DEFAULT 0,
    rating DECIMAL(3, 2) NOT NULL DEFAULT 0.00,
    reviews INT NOT NULL DEFAULT 0,
    featured BOOLEAN NOT NULL DEFAULT FALSE,
    is_new BOOLEAN NOT NULL DEFAULT FALSE,
    FOREIGN KEY (brand_id) REFERENCES brands (id),
    FOREIGN KEY (category_id) REFERENCES categories (id),
    FOREIGN KEY (movement_id) REFERENCES movements (id),
    FOREIGN KEY (case_material_id) REFERENCES case_materials (id)
);

-- Additional images per watch (replaces JSON `images` column — 1NF)
CREATE TABLE IF NOT EXISTS watch_images (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    watch_id INT NOT NULL,
    image_url TEXT NOT NULL,
    sort_order SMALLINT NOT NULL DEFAULT 0,  -- controls display order
    FOREIGN KEY (watch_id) REFERENCES watches (id) ON DELETE CASCADE
);

-- ── Orders ───────────────────────────────────────────────────

DO $$
BEGIN
  CREATE TYPE order_status AS ENUM ('Pending', 'Processing', 'Shipped', 'Delivered', 'Cancelled');
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

DO $$
BEGIN
  CREATE TYPE payment_method AS ENUM ('COD', 'Card');
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

CREATE TABLE IF NOT EXISTS orders (
    id VARCHAR(36) PRIMARY KEY,
    user_id INT NOT NULL,
    address_id INT NOT NULL,            -- FK to snapshot of shipping address
    total DECIMAL(12, 2) NOT NULL,
    status ORDER_STATUS NOT NULL DEFAULT 'Pending',
    payment_method PAYMENT_METHOD NOT NULL,
    tracking_number VARCHAR(255) DEFAULT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    FOREIGN KEY (address_id) REFERENCES user_addresses (id)
);

CREATE TABLE IF NOT EXISTS order_items (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id VARCHAR(36) NOT NULL,
    watch_id INT NOT NULL,
    quantity INT NOT NULL,
    unit_price DECIMAL(12, 2) NOT NULL,   -- price snapshot at time of purchase
    FOREIGN KEY (order_id) REFERENCES orders (id) ON DELETE CASCADE,
    FOREIGN KEY (watch_id) REFERENCES watches (id) ON DELETE CASCADE
);

CREATE OR REPLACE FUNCTION SET_UPDATED_AT()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = CURRENT_TIMESTAMP;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS users_set_updated_at ON users;
CREATE TRIGGER users_set_updated_at
BEFORE UPDATE ON users
FOR EACH ROW
EXECUTE FUNCTION SET_UPDATED_AT();
