name: Database Pipeline

on:
  push:
    branches: [ main ]
    paths:
      - 'db/**'
      - '.github/workflows/database-pipeline.yaml'
  workflow_dispatch:
  workflow_run:
    workflows: ["terraform"]
    types:
      - completed
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check-syntax:
    runs-on: ubuntu-latest
    defaults: 
      run:
       working-directory:  ./db
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python for SQL Linter
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install SQLFluff Linter
        run: pip install sqlfluff

      - name: Check SQL Syntax
        run: |
          sqlfluff lint . --dialect postgres || echo "SQL Formatting Warnings Detected"
  test-migration:
    needs: check-syntax
    runs-on: ubuntu-latest
    defaults: 
      run:
       working-directory:  ./db
    services:
      postgres-test:
        image: postgres:16-alpine
        env:
          POSTGRES_DB: test_watch_store
          POSTGRES_USER: test_user
          POSTGRES_PASSWORD: test_password
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 5s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install PostgreSQL Client
        run: sudo apt-get update && sudo apt-get install -y postgresql-client

      - name: Wait for PostgreSQL
        env:
          PGPASSWORD: test_password
        run: |
          until pg_isready -h localhost -p 5432 -U test_user; do
            echo "Waiting for PostgreSQL service to be ready..."
            sleep 2
          done

      - name: Test Apply SQL Schema
        env:
          PGPASSWORD: test_password
        run: |
          echo "Testing schema deployment on ephemeral database..."
          psql -h localhost -U test_user -d test_watch_store -v  ON_ERROR_STOP=1 -f schema.sql

      - name: Test Seed Data Injection
        env:
          PGPASSWORD: test_password
        run: |
          echo "Testing seed data deployment..."
          psql -h localhost -U test_user -d test_watch_store -v  ON_ERROR_STOP=1 -f seed.sql
  deploy:
      needs: test-migration
      if: ${{ github.event_name != 'workflow_run' || github.event.workflow_run.conclusion == 'success' }}
      runs-on: self-hosted
      defaults:
        run: 
          working-directory: ./db
      steps:
         - name: checkout code
           uses: actions/checkout@v7
         - name: Fetch Credentials & Run Migrations on RDS
           run: |
             SECRET_JSON=$(aws secretsmanager get-secret-value \
             --secret-id "prod/db-secrets" \
             --region eu-north-1 \
             --query SecretString \
             --output text)

          
             DB_HOST=$(echo $SECRET_JSON | jq -r '.DB_HOST')
             DB_USER=$(echo $SECRET_JSON | jq -r '.DB_USER')
             DB_PASS=$(echo $SECRET_JSON | jq -r '.DB_PASSWORD')
             DB_NAME=watch_store
             DB_PORT=5432         
             export PGPASSWORD="$DB_PASS"
             echo "Connecting to RDS PostgreSQL at $DB_HOST..."
             for file in $(ls *.sql 2>/dev/null | sort -V); do
             echo "Applying $file..."
             psql -h "$DB_HOST" -U "$DB_USER" -d "$DB_NAME" -p "$DB_PORT" -v ON_ERROR_STOP=1 -f "$file"
             done
             echo "All migrations successfully executed on RDS!" 